travis:
  secure:
    BINSTAR_TOKEN: n9gbRl72lg09+McD44f9nNZwQtBxgmO7dWNmYV45EZ1HCfWXNxPeK5XotA5YW3rgY2MyWdoB2nYHek0ARMPaBISPrPBhC7RO50jnV5PMJWe7vqpCaWhcYdR+4EMUUBuH4SRrtuaBbvQ6NfbvtpnkpffUMjF5thLRdQ2A6i8udbGu6mRQJIENoMvYzOSvVooZLiHDguN9PKEq6OekYSmU5K/U+JYWYFVSMc04ZVV0HgE9PN38Q/OM/SaTVTAhohpkM4Hpn1m2JF1EkvOxkIHfLtsXDFxkzkXB/4G1SApgru2Sw8sQpN2YgQ+ImkeyT4eDXzT64Euql/xCSK5mXKWJtNlFDMf9/SATmpjug1zU3ThbzTZdxG3oltMbkb84BLUMEuPQkeRe4dFW7ZYxkDw1RCjsXllF/n6btSTSCfBcDUNp5WCKNgQh0C67PxpU4dRrRU3R9PXgyOM1HCUpiJNoYl+sqDKTOchV7c6hEcYABQN+Vd7uTnZoeFW6hineFFDyAjxtxalxMz+RIXc4WgWFYqWcZ0g9OvW7PslCF1WtAHzINb2rPYaxqyKRlfedpMSR9z7xcL01e7+JR+t/zvkH3xqqdBQFMP1hk8mVZdUzXps/KYG/wxV6r1/KZwOZjYP/rmW+djEFnwh+tULaqA/1CfeYf3ez8Sq+OILKLmzHbI0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
