travis:
  secure:
    BINSTAR_TOKEN: XHjBJqvfq/FUmAVH5uX2BBvTigpqNDwnsyKA2i6gSFj8Pm1JG//xpcPLjq+jMOcDlww3dAxH0tBiBCVLRQlkPF0qblZNfIPPYGd5d8EnStgYdytvvo9Heptry9EXe58+EHaLPdHooYJOU0kznPKPjnB05A4PKUxT8RtFCakj/P68OTJWvtAj9egIrYu783bzvI75Pcfrb+RdcIDNdnmrchyjiq+uSJjGVMwtNFpNe7jB1PKjYdeIua1kNvdx8waBon0nVCIEek+TH4lWPogROkBkWd6QgqJ8Vmb4Nsn2yS04Ua9klTexR6PLglt5C8bV2ILat+o7Q6uGXAho8Hj1UuFUfYaVPskfHJQJVolhNenlCe16FuuP089OnjaIvZbXS/PXliJx7aTvW3itWU61xEKc3RCnMfnPRVXBU8+74whCgkKLQ+IjpX5EO3/5cQejYHwQ9OK8Kn1l9ZucIn0XX60TN2PcmCdNkC/jY5bPgSKnJQ1b1oEtZMgx+Qn6tfeY3ypVtEAe2h4FaYB20r4NAwXZgaMdOxa3dG5gKwji5DnFlbfM8w1ZhrYP0FDL2th2HEhWjW3tnOxRlUbtb4Eq9IVCLu+ckUDvhMSFy7iQ4jtlKyOd5PaUE4A/VxH3MgmUsAqJlHRAQrwOjzsT1MiVjdEk+SpSKH5wBEPE5VuQxDA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
